//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.UnitTest.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;title&gt;Reservation Request Details&lt;/title&gt;
        ///
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///    /* Client-specific Styles */
        ///
        ///    div,
        ///    p,
        ///    a,
        ///    li,
        ///    td {
        ///      -webkit-text-size-adjust: none;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;title&gt;Reservation Request Details&lt;/title&gt;
        ///
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///    /* Client-specific Styles */
        ///
        ///    div,
        ///    p,
        ///    a,
        ///    li,
        ///    td {
        ///      -webkit-text-size-adjust: none;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emailtemplatebooking {
            get {
                return ResourceManager.GetString("emailtemplatebooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;title&gt;New Booking&lt;/title&gt;
        ///
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///    /* Client-specific Styles */
        ///    div,
        ///    p,
        ///    a,
        ///    li,
        ///    td {
        ///      -webkit-text-size-adjust: none;
        ///    }
        ///
        ///    #outloo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string irebooking {
            get {
                return ResourceManager.GetString("irebooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;numberOfPeople&quot;:&quot;2&quot;,&quot;name&quot;:&quot;bingliang chen&quot;,&quot;phoneNumber&quot;:&quot;0860107230&quot;,&quot;email&quot;:&quot;bingliangchan@gmail.com&quot;,&quot;tour&quot;:{&quot;name&quot;:&quot;Aran Islands (Inisheer) and Cliffs of Moher&quot;,&quot;price&quot;:40,&quot;countryId&quot;:1,&quot;ratingNumber&quot;:4,&quot;tagCat&quot;:1,&quot;content&quot;:&quot;\t\t\t&lt;div id=\&quot;single_tour_feat\&quot;&gt;\r\n\t\t\t\t\t\t&lt;ul&gt;\r\n\t\t\t\t\t\t\t&lt;li&gt;\r\n\t\t\t\t\t\t\t\t&lt;i class=\&quot;icon_set_1_icon-83\&quot;&gt;&lt;/i&gt;1 Day\r\n\t\t\t\t\t\t\t&lt;/li&gt;\r\n\t\t\t\t\t\t\t&lt;li&gt;\r\n\t\t\t\t\t\t\t\t&lt;i class=\&quot;icon_set_1_icon-14\&quot;&gt;&lt;/i&gt;Lunch not included\r\n\t\t\t\t\t\t\t&lt;/li&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string objJSon {
            get {
                return ResourceManager.GetString("objJSon", resourceCulture);
            }
        }
    }
}
